[build]
    command = "npm run build"
    functions = "functions"
    publish = "images"

[build.environment]
    CHANNEL_SECRET="076051b8e85f56934a885a3f50fc45ed"
    CHANNEL_ACCESS_TOKEN="FBWOmugoiApfBVVQ+0R3OmOxkf2a11hO26dgduqIjEhHMb66J9T8YZnrpHFUeq7IOn7UbCNyF7Y1zY91PyQ9potq4ch0KxZIO6cfA4+rtuhehfERUKDMJDEksI69v7erWTu6uZr6CT1Xa9CAHMnDawdB04t89/1O/w1cDnyilFU="
    NETLIFY_URL="https://goofy-nobel-5c0168.netlify.app"
