[build]
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[build.environment]
    CHANNEL_SECRET="XXXXXXXXXXXXXXXXXXXXXXXXXX"
    CHANNEL_ACCESS_TOKEN="XXXXXXXXXXXXXXXXXXXXXXXXXX"
    NETLIFY_URL="https://XXXXX-XXXXX-XXXXXX.netlify.app"
